apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-healer
  namespace: k8s-healer
  labels:
    app: k8s-healer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-healer
  template:
    metadata:
      labels:
        app: k8s-healer
    spec:
      serviceAccountName: k8s-healer
      containers:
        - name: agent
          image: ghcr.io/mayur0522/k8s-healer:latest
          env:
            - name: AZURE_OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-config
                  key: AZURE_OPENAI_API_KEY
            - name: AZURE_OPENAI_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: ai-config
                  key: AZURE_OPENAI_ENDPOINT
            - name: AZURE_DEPLOYMENT_NAME
              value: "gpt-4o"
            - name: DRY_RUN
              value: "true"
            - name: ARGOCD_SAFE_MODE
              value: "true"
            - name: MAX_AI_CALLS_PER_HOUR
              value: "30"
            - name: EXCLUDED_NAMESPACES
              value: "kube-system,kube-public,k8s-healer,argocd,cert-manager,vault,flux-system,ingress-nginx,keda,external-secrets"
            - name: COOLDOWN_SECONDS
              value: "300"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
